travis:
  secure:
    BINSTAR_TOKEN: fk+plGmAOfPLs9QyGIZYlqabrgMgB6R+rJobWeg2+kKyiTRCq/QmN7Xtiz09pQa8pjnMGJoL/g5K0xdcRKBOoGGDzCO6j2vf/DSnaSwiKe4J3qq3UZxZ4oCcJa4g/JWAwJItm7MOtBwm3hy4NSZ1Tb36eGSkb3CURtIxrZ2HA7bQWHb9zgRYj/IAcEmOTeVasUCMJHrDGNWNu1Y/l7l0xjqS7apPTQdL2DyZUoghVQbAKUr5GajPT8gy3OiU4cezQhNoUJiZ9VQPhipfmZZ0H3KfNOzfYqQG81zK8FNTzG/RnhatRcrZmCv/HxrRHUv1upgBvl4nsID5xBBFuQWjEj2C8PmSTPVnJUGjflQMf17IDkNZgh75cuaHvmzjeEX2NraXHWRD35b9hm+wQhoWBxVh6e9BcbOTDMLMpNJxY8rDMzZucZGuRtpWAv2OrQNbfVAGHBsf9GyMUvtPn8C28ZIXzrqW0BQSX7f8meK7Qcbxy6eejIRQobiYZtVhHrMlvqgzoH/hChow2jZdN+wjtTVIyhNWPvywo17igP/cFCFMkZ+k5WPl5WxpLjYUMTz/AkbjkWPAstOShP+qI4NJRGhXHydW+OiyhhWMqMgIy7INSxmP57Vp3gxwgmPVEGum4jthApsWBlLUyzSI3dO5WRuDlSCwzf6O0wj3pGgnJRQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
